name:                sentiwordnet-parser
version:             0.2.0.0
synopsis:            Parser for the SentiWordNet tab-separated file
description:         Parser for the SentiWordNet tab-separated file
homepage:            https://github.com/k-bx/sentiwordnet-parser#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Natural Language Processing
extra-source-files:
- README.md

dependencies:
  - trifecta
  - parsers
  - base >= 4.7 && < 5
  - Decimal
  - text
  - safe
  - string-class
  - vector
  - unordered-containers
  - hashable

library:
  source-dirs:      src
  ghc-options:      -Wall
