name:                sentiwordnet-parser
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/sentiwordnet-parser#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - trifecta
  - parsers
  - base >= 4.7 && < 5
  - Decimal
  - text
  - safe
  - string-class
  - vector

executables:
  sentiwordnet-parser:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -Wall
